services:
   bot-fy2:
      image: bot-fy
      env_file:
        - .env
      build: 
          context: ./bot-fy
          dockerfile: docker/Dockerfile
      restart: always
      environment:
          - TZ=America/Sao_Paulo
      volumes: 
          - musics:/music:ro
      deploy:
          resources:
              limits:
                  memory: 1G

volumes:
  musics:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.2.5,rw
      device: ":/mnt/cloud/nextcloud/__groupfolders/1/Musicas"